import asyncio

async def service(data: dict):
    insurances = [
        {
            "product_id": "CANCER_A01",
            "insurer": "GenLife",
            "product_name": "GenLife 암케어 베이직",
            "category": "cancer",
            "monthly_premium": 39000,
            "renewal_type": "non_renewable",
            "coverage_period": "age_90",
            "entry_age_min": 20,
            "entry_age_max": 55,
            "coverage": {
                "general_cancer_diagnosis": 30000000,
                "minor_cancer_diagnosis": 5000000,
                "cancer_surgery": 3000000,
                "cancer_hospitalization_per_day": 50000,
            },
            "waiting_period_days": 90,
            "reduction_period_months": 12,
            "reduction_rate": 0.5,
            "special_features": ["낮은 월 보험료", "비갱신형", "기본적인 암 보장 중심"],
            "limitations": ["암 진단비가 비교적 낮음", "유사암 보장이 낮음"],
        },
        {
            "product_id": "CANCER_B01",
            "insurer": "Nova Insurance",
            "product_name": "Nova 암진단 플러스",
            "category": "cancer",
            "monthly_premium": 49000,
            "renewal_type": "non_renewable",
            "coverage_period": "age_90",
            "entry_age_min": 20,
            "entry_age_max": 60,
            "coverage": {
                "general_cancer_diagnosis": 50000000,
                "minor_cancer_diagnosis": 10000000,
                "cancer_surgery": 3000000,
                "cancer_hospitalization_per_day": 50000,
            },
            "waiting_period_days": 90,
            "reduction_period_months": 12,
            "reduction_rate": 0.5,
            "special_features": ["높은 일반암 진단비", "비갱신형", "진단비 중심 설계"],
            "limitations": ["월 보험료가 상대적으로 높음", "수술비 보장은 평균 수준"],
        },
        {
            "product_id": "CANCER_C01",
            "insurer": "BlueTree Insurance",
            "product_name": "BlueTree 스마트 암보험",
            "category": "cancer",
            "monthly_premium": 31000,
            "renewal_type": "renewable",
            "renewal_cycle_years": 10,
            "coverage_period": "age_100",
            "entry_age_min": 20,
            "entry_age_max": 65,
            "coverage": {
                "general_cancer_diagnosis": 40000000,
                "minor_cancer_diagnosis": 7000000,
                "cancer_surgery": 3000000,
                "cancer_hospitalization_per_day": 50000,
            },
            "waiting_period_days": 90,
            "reduction_period_months": 12,
            "reduction_rate": 0.5,
            "special_features": [
                "초기 보험료가 낮음",
                "최대 100세 보장",
                "진단비 대비 보험료가 저렴함",
            ],
            "limitations": ["10년 갱신형", "갱신 시 보험료가 인상될 수 있음"],
        },
        {
            "product_id": "CANCER_D01",
            "insurer": "EverCare Life",
            "product_name": "EverCare 암수술 안심보험",
            "category": "cancer",
            "monthly_premium": 47000,
            "renewal_type": "non_renewable",
            "coverage_period": "age_90",
            "entry_age_min": 25,
            "entry_age_max": 60,
            "coverage": {
                "general_cancer_diagnosis": 35000000,
                "minor_cancer_diagnosis": 7000000,
                "cancer_surgery": 10000000,
                "cancer_hospitalization_per_day": 80000,
            },
            "waiting_period_days": 90,
            "reduction_period_months": 12,
            "reduction_rate": 0.5,
            "special_features": ["높은 암 수술비", "높은 입원 일당", "비갱신형"],
            "limitations": ["진단비는 중간 수준", "수술·입원 보장 비중이 높음"],
        },
        {
            "product_id": "CANCER_E01",
            "insurer": "Mirae Health",
            "product_name": "Mirae 유사암 케어",
            "category": "cancer",
            "monthly_premium": 45000,
            "renewal_type": "non_renewable",
            "coverage_period": "age_90",
            "entry_age_min": 20,
            "entry_age_max": 55,
            "coverage": {
                "general_cancer_diagnosis": 30000000,
                "minor_cancer_diagnosis": 20000000,
                "cancer_surgery": 3000000,
                "cancer_hospitalization_per_day": 50000,
            },
            "waiting_period_days": 90,
            "reduction_period_months": 6,
            "reduction_rate": 0.5,
            "special_features": [
                "높은 유사암 진단비",
                "감액기간이 비교적 짧음",
                "비갱신형",
            ],
            "limitations": [
                "일반암 진단비가 낮음",
                "일반암 중심 사용자에게는 효율이 낮을 수 있음",
            ],
        },
        {
            "product_id": "CANCER_F01",
            "insurer": "OneShield Life",
            "product_name": "OneShield 프리미엄 암보험",
            "category": "cancer",
            "monthly_premium": 65000,
            "renewal_type": "non_renewable",
            "coverage_period": "age_100",
            "entry_age_min": 20,
            "entry_age_max": 60,
            "coverage": {
                "general_cancer_diagnosis": 70000000,
                "minor_cancer_diagnosis": 15000000,
                "cancer_surgery": 10000000,
                "cancer_hospitalization_per_day": 100000,
            },
            "waiting_period_days": 90,
            "reduction_period_months": 6,
            "reduction_rate": 0.5,
            "special_features": [
                "높은 일반암 진단비",
                "높은 수술비",
                "100세 보장",
                "비갱신형",
            ],
            "limitations": ["월 보험료가 높음"],
        },
        {
            "product_id": "CANCER_G01",
            "insurer": "SimpleCare",
            "product_name": "SimpleCare 라이트 암보험",
            "category": "cancer",
            "monthly_premium": 25000,
            "renewal_type": "renewable",
            "renewal_cycle_years": 5,
            "coverage_period": "age_90",
            "entry_age_min": 20,
            "entry_age_max": 70,
            "coverage": {
                "general_cancer_diagnosis": 20000000,
                "minor_cancer_diagnosis": 3000000,
                "cancer_surgery": 2000000,
                "cancer_hospitalization_per_day": 30000,
            },
            "waiting_period_days": 90,
            "reduction_period_months": 12,
            "reduction_rate": 0.5,
            "special_features": [
                "가장 저렴한 초기 보험료",
                "가입 가능 연령 범위가 넓음",
            ],
            "limitations": [
                "5년 갱신형",
                "보장 금액이 전반적으로 낮음",
                "갱신 시 보험료 변동 가능",
            ],
        },
        {
            "product_id": "CANCER_H01",
            "insurer": "Balance Life",
            "product_name": "Balance 종합 암케어",
            "category": "cancer",
            "monthly_premium": 52000,
            "renewal_type": "non_renewable",
            "coverage_period": "age_100",
            "entry_age_min": 20,
            "entry_age_max": 60,
            "coverage": {
                "general_cancer_diagnosis": 45000000,
                "minor_cancer_diagnosis": 10000000,
                "cancer_surgery": 7000000,
                "cancer_hospitalization_per_day": 70000,
            },
            "waiting_period_days": 90,
            "reduction_period_months": 6,
            "reduction_rate": 0.5,
            "special_features": [
                "진단비와 수술비가 균형적",
                "100세 보장",
                "비갱신형",
                "감액기간 6개월",
            ],
            "limitations": ["월 5만 원 예산을 소폭 초과"],
        },
    ]
    return insurances


if __name__ == "__main__":
    print(asyncio.run(service({})))